#!/usr/bin/env bash
# Display visitor IP and HTTP status code from Apache access log
# Format: IP HTTP_CODE
# The apache-access.log file must be in the same directory as this script

awk '{print $1, $9}' apache-access.log
