#!/usr/bin/env bash
# Print "To infinity and beyond" indefinitely and react to SIGTERM

# Trap SIGTERM and print "I am invincible!!!"
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
